-- PROT.FRONTMATTER.ROLE.FILE — Seed: reference URLs
-- Re-generate: ruby schema/url.rb

INSERT OR IGNORE INTO reference_urls (language, section, url, roles) VALUES
  ('C', 'ISO/IEC 9899:1999 §6.3.2.1 Lvalues', 'https://c0x.shape-of-code.com/6.3.2.1.html', 'C.OBJECT, C.SUBJECT'),
  ('C', 'ISO/IEC 9899:1999 §6.5.16 Assignment operators', 'https://c0x.shape-of-code.com/6.5.16.html', 'C.ACTION, C.OBJECT, C.SUBJECT'),
  ('C', 'ISO/IEC 9899:1999 §6.5 Expressions', 'https://c0x.shape-of-code.com/6.5.html', 'C.ACTION, C.OBJECT'),
  ('C', 'ISO/IEC 9899:1999 §6.7 Declarations', 'https://c0x.shape-of-code.com/6.7.html', 'C.SUBJECT'),
  ('C', 'ISO/IEC 9899:1999 §6.8 Statements and blocks', 'https://c0x.shape-of-code.com/6.8.html', 'C.ACTION'),
  ('Rust', 'Rust Reference §Expressions', 'https://doc.rust-lang.org/reference/expressions.html', 'RUST.ACTION'),
  ('Rust', 'Rust Reference §Expressions — Evaluation order of operands', 'https://doc.rust-lang.org/reference/expressions.html#evaluation-order-of-operands', 'RUST.ACTION'),
  ('Rust', 'Rust Reference §Expressions — Moved and copied types', 'https://doc.rust-lang.org/reference/expressions.html#moved-and-copied-types', 'RUST.ACTION, RUST.OBJECT'),
  ('Rust', 'Rust Reference §Expressions — Place expressions and value expressions', 'https://doc.rust-lang.org/reference/expressions.html#place-expressions-and-value-expressions', 'RUST.ACTION, RUST.OBJECT, RUST.SUBJECT'),
  ('Rust', 'Rust Reference §Items', 'https://doc.rust-lang.org/reference/items.html', 'RUST.SUBJECT'),
  ('Rust', 'Rust Reference §Types', 'https://doc.rust-lang.org/reference/types.html', 'RUST.OBJECT, RUST.SUBJECT'),
  ('SageMath', 'SageMath 10.8 Reference Manual — Category Framework', 'https://doc.sagemath.org/html/en/reference/categories/index.html', 'SAGEMATH.OBJECT, SAGEMATH.SUBJECT'),
  ('SageMath', 'SageMath 10.8 Reference Manual — Dynamic hierarchy of classes', 'https://doc.sagemath.org/html/en/reference/categories/sage/categories/primer.html#dynamic-hierarchy-of-classes', 'SAGEMATH.ACTION'),
  ('SageMath', 'SageMath 10.8 Reference Manual — Elements, Parents, and Categories: a primer §Elements, Parents, Categories', 'https://doc.sagemath.org/html/en/reference/categories/sage/categories/primer.html#elements-parents-and-categories', 'SAGEMATH.ACTION, SAGEMATH.OBJECT, SAGEMATH.SUBJECT'),
  ('SageMath', 'SageMath 10.8 Reference Manual — The coercion model', 'https://doc.sagemath.org/html/en/reference/coercion/sage/structure/coerce.html', 'SAGEMATH.ACTION, SAGEMATH.OBJECT, SAGEMATH.SUBJECT'),
  ('SageMath', 'SageMath 10.8 Reference Manual — Set of all objects of a given Python class', 'https://doc.sagemath.org/html/en/reference/sets/sage/sets/pythonclass.html', 'SAGEMATH.OBJECT, SAGEMATH.SUBJECT'),
  ('SageMath', 'SageMath 10.8 Tutorial — Programming §Creating Compiled Code', 'https://doc.sagemath.org/html/en/tutorial/programming.html#creating-compiled-code', 'SAGEMATH.ACTION'),
  ('SageMath', 'SageMath 10.8 Tutorial — Programming §Lists, Tuples, and Sequences', 'https://doc.sagemath.org/html/en/tutorial/programming.html#lists-tuples-and-sequences', 'SAGEMATH.OBJECT'),
  ('SageMath', 'SageMath 10.8 Tutorial — Programming §Loading and Attaching Sage files', 'https://doc.sagemath.org/html/en/tutorial/programming.html#loading-and-attaching-sage-files', 'SAGEMATH.ACTION'),
  ('Java', 'JLS §12 Execution', 'https://docs.oracle.com/en/java/javase/26/docs/specs/jls/jls-12.html', 'JAVA.SUBJECT'),
  ('Java', 'JLS §14 Blocks, Statements, and Patterns', 'https://docs.oracle.com/en/java/javase/26/docs/specs/jls/jls-14.html', 'JAVA.ACTION'),
  ('Java', 'JLS §14.1 Normal and Abrupt Completion of Statements', 'https://docs.oracle.com/en/java/javase/26/docs/specs/jls/jls-14.html#jls-14.1', 'JAVA.ACTION'),
  ('Java', 'JLS §15.1 Evaluation, Denotation, and Result', 'https://docs.oracle.com/en/java/javase/26/docs/specs/jls/jls-15.html', 'JAVA.OBJECT'),
  ('Java', 'JLS §15.12.4 Run-Time Evaluation of Method Invocation', 'https://docs.oracle.com/en/java/javase/26/docs/specs/jls/jls-15.html#jls-15.12.4', 'JAVA.ACTION, JAVA.SUBJECT'),
  ('Java', 'JLS §4 Types, Values, and Variables', 'https://docs.oracle.com/en/java/javase/26/docs/specs/jls/jls-4.html', 'JAVA.OBJECT'),
  ('Java', 'JLS §8 Classes', 'https://docs.oracle.com/en/java/javase/26/docs/specs/jls/jls-8.html', 'JAVA.SUBJECT'),
  ('Python', 'Python 3.14 §3.1 Objects, Values, and Types', 'https://docs.python.org/3/reference/datamodel.html#objects-values-and-types', 'PYTHON.OBJECT'),
  ('Python', 'Python 3.14 §3.3 Special Method Names', 'https://docs.python.org/3/reference/datamodel.html#special-method-names', 'PYTHON.OBJECT'),
  ('Python', 'Python 3.14 §4.3 Exceptions', 'https://docs.python.org/3/reference/executionmodel.html#exceptions', 'PYTHON.ACTION'),
  ('Python', 'Python 3.14 §4.2 Naming and Binding', 'https://docs.python.org/3/reference/executionmodel.html#naming-and-binding', 'PYTHON.ACTION, PYTHON.SUBJECT'),
  ('Python', 'Python 3.14 §4.4.2 Python Runtime Model', 'https://docs.python.org/3/reference/executionmodel.html#python-runtime-model', 'PYTHON.SUBJECT'),
  ('Python', 'Python 3.14 §4.4 Runtime Components', 'https://docs.python.org/3/reference/executionmodel.html#runtime-components', 'PYTHON.SUBJECT'),
  ('Python', 'Python 3.14 §4.1 Structure of a Program', 'https://docs.python.org/3/reference/executionmodel.html#structure-of-a-program', 'PYTHON.ACTION, PYTHON.SUBJECT'),
  ('Racket', 'Racket Reference §1.1 Evaluation Model', 'https://docs.racket-lang.org/reference/eval-model.html#%28part._.Evaluation_.Model%29', 'RACKET.ACTION, RACKET.OBJECT'),
  ('Racket', 'Racket Reference §1.1.5 Objects and Imperative Update', 'https://docs.racket-lang.org/reference/eval-model.html#%28part._.Objects_.And_.Imperative_.Update%29', 'RACKET.OBJECT, RACKET.SUBJECT'),
  ('Racket', 'Racket Reference §1.1.7 Procedure Applications and Local Variables', 'https://docs.racket-lang.org/reference/eval-model.html#%28part._.Procedure_.Applications_.And_.Local_.Variables%29', 'RACKET.ACTION, RACKET.SUBJECT'),
  ('Racket', 'Racket Reference §1.1.1 Sub-expression Evaluation and Continuations', 'https://docs.racket-lang.org/reference/eval-model.html#%28part._.Sub_expression_.Evaluation_.And_.Continuations%29', 'RACKET.ACTION, RACKET.OBJECT'),
  ('Racket', 'Racket Reference §1.1.2 Tail Position', 'https://docs.racket-lang.org/reference/eval-model.html#%28part._.Tail_.Position%29', 'RACKET.ACTION'),
  ('Racket', 'Racket Reference §1.1.4 Top-Level Variables', 'https://docs.racket-lang.org/reference/eval-model.html#%28part._.Top_Level_.Variables%29', 'RACKET.SUBJECT'),
  ('Racket', 'Racket Reference §1.1.8 Variables and Locations', 'https://docs.racket-lang.org/reference/eval-model.html#%28part._.Variables_.And_.Locations%29', 'RACKET.SUBJECT'),
  ('Ruby', 'Ruby 3.4 Assignment', 'https://docs.ruby-lang.org/en/3.4/syntax/assignment_rdoc.html', 'RUBY.SUBJECT'),
  ('Ruby', 'Ruby 3.4 Control Expressions', 'https://docs.ruby-lang.org/en/3.4/syntax/control_expressions_rdoc.html', 'RUBY.ACTION'),
  ('Ruby', 'Ruby 3.4 Control Expressions §Modifier Statements', 'https://docs.ruby-lang.org/en/3.4/syntax/control_expressions_rdoc.html#modifier-statements', 'RUBY.OBJECT'),
  ('Ruby', 'Ruby 3.4 Exceptions', 'https://docs.ruby-lang.org/en/3.4/syntax/exceptions_rdoc.html', 'RUBY.ACTION'),
  ('Ruby', 'Ruby 3.4 Methods', 'https://docs.ruby-lang.org/en/3.4/syntax/methods_rdoc.html', 'RUBY.ACTION'),
  ('Ruby', 'Ruby 3.4 Miscellaneous', 'https://docs.ruby-lang.org/en/3.4/syntax/miscellaneous_rdoc.html', 'RUBY.ACTION'),
  ('Ruby', 'Ruby 3.4 Miscellaneous §defined?', 'https://docs.ruby-lang.org/en/3.4/syntax/miscellaneous_rdoc.html#defined?', 'RUBY.SUBJECT'),
  ('Ruby', 'Ruby 3.4 Modules and Classes §Inheritance', 'https://docs.ruby-lang.org/en/3.4/syntax/modules_and_classes_rdoc.html#inheritance', 'RUBY.ACTION'),
  ('Ruby', 'Ruby 3.4 Modules and Classes §Scope', 'https://docs.ruby-lang.org/en/3.4/syntax/modules_and_classes_rdoc.html#scope', 'RUBY.SUBJECT'),
  ('Ruby', 'Ruby 3.4 Modules and Classes §Singleton Classes', 'https://docs.ruby-lang.org/en/3.4/syntax/modules_and_classes_rdoc.html#singleton-classes', 'RUBY.SUBJECT'),
  ('Ruby', 'Ruby 3.4 Modules and Classes §Visibility', 'https://docs.ruby-lang.org/en/3.4/syntax/modules_and_classes_rdoc.html#visibility', 'RUBY.ACTION'),
  ('Ruby', 'Ruby 3.4 Operators', 'https://docs.ruby-lang.org/en/3.4/syntax/operators_rdoc.html', 'RUBY.ACTION'),
  ('Ruby', 'Ruby 3.4 Pattern Matching', 'https://docs.ruby-lang.org/en/3.4/syntax/pattern_matching_rdoc.html', 'RUBY.ACTION'),
  ('Ruby', 'Ruby 3.4 Precedence', 'https://docs.ruby-lang.org/en/3.4/syntax/precedence_rdoc.html', 'RUBY.ACTION, RUBY.OBJECT'),
  ('Ruby', 'Ruby 4.1 Calling Methods §Arguments', 'https://docs.ruby-lang.org/en/master/syntax/calling_methods_rdoc.html#arguments', 'RUBY.OBJECT'),
  ('Ruby', 'Ruby 4.1 Calling Methods §Block Argument', 'https://docs.ruby-lang.org/en/master/syntax/calling_methods_rdoc.html#block-argument', 'RUBY.OBJECT'),
  ('Ruby', 'Ruby 4.1 Calling Methods §Chaining', 'https://docs.ruby-lang.org/en/master/syntax/calling_methods_rdoc.html#chaining-method-calls', 'RUBY.SUBJECT'),
  ('Ruby', 'Ruby 4.1 Calling Methods §Keyword Arguments', 'https://docs.ruby-lang.org/en/master/syntax/calling_methods_rdoc.html#keyword-arguments', 'RUBY.OBJECT'),
  ('Ruby', 'Ruby 4.1 Calling Methods §Method Lookup', 'https://docs.ruby-lang.org/en/master/syntax/calling_methods_rdoc.html#method-lookup', 'RUBY.ACTION'),
  ('Ruby', 'Ruby 4.1 Calling Methods §Positional Arguments', 'https://docs.ruby-lang.org/en/master/syntax/calling_methods_rdoc.html#positional-arguments', 'RUBY.OBJECT'),
  ('Ruby', 'Ruby 4.1 Calling Methods §Proc to Block Conversion', 'https://docs.ruby-lang.org/en/master/syntax/calling_methods_rdoc.html#proc-to-block-conversion', 'RUBY.OBJECT'),
  ('Ruby', 'Ruby 4.1 Calling Methods §Receiver', 'https://docs.ruby-lang.org/en/master/syntax/calling_methods_rdoc.html#receiver', 'RUBY.ACTION, RUBY.SUBJECT'),
  ('Ruby', 'Ruby 4.1 Calling Methods §Safe Navigation', 'https://docs.ruby-lang.org/en/master/syntax/calling_methods_rdoc.html#safe-navigation-operator', 'RUBY.SUBJECT'),
  ('Ruby', 'Ruby 4.1 Calling Methods §Unpacking Positional Arguments', 'https://docs.ruby-lang.org/en/master/syntax/calling_methods_rdoc.html#unpacking-positional-arguments', 'RUBY.OBJECT'),
  ('Scala', 'Scala Collections Overview', 'https://docs.scala-lang.org/overviews/collections-2.13/overview.html', 'SCALA.OBJECT, SCALA.SUBJECT'),
  ('Forth', 'Forth 2012 §6.1 Core Words', 'https://forth-standard.org/standard/core', 'FORTH.ACTION, FORTH.OBJECT, FORTH.SUBJECT'),
  ('Forth', 'Forth 2012 Foreword', 'https://forth-standard.org/standard/foreword', 'FORTH.ACTION, FORTH.OBJECT, FORTH.SUBJECT'),
  ('Go', 'Go Spec §Address operators', 'https://go.dev/ref/spec#Address_operators', 'GO.SUBJECT'),
  ('Go', 'Go Spec §Constants', 'https://go.dev/ref/spec#Constants', 'GO.OBJECT'),
  ('Go', 'Go Spec §Defer statements', 'https://go.dev/ref/spec#Defer_statements', 'GO.ACTION'),
  ('Go', 'Go Spec §Expressions', 'https://go.dev/ref/spec#Expressions', 'GO.ACTION'),
  ('Go', 'Go Spec §Go statements', 'https://go.dev/ref/spec#Go_statements', 'GO.ACTION'),
  ('Go', 'Go Spec §Order of evaluation', 'https://go.dev/ref/spec#Order_of_evaluation', 'GO.ACTION'),
  ('Go', 'Go Spec §Program execution', 'https://go.dev/ref/spec#Program_execution', 'GO.ACTION, GO.SUBJECT'),
  ('Go', 'Go Spec §Properties of types and values', 'https://go.dev/ref/spec#Properties_of_types_and_values', 'GO.OBJECT'),
  ('Go', 'Go Spec §Select statements', 'https://go.dev/ref/spec#Select_statements', 'GO.ACTION'),
  ('Go', 'Go Spec §Short variable declarations', 'https://go.dev/ref/spec#Short_variable_declarations', 'GO.SUBJECT'),
  ('Go', 'Go Spec §Statements', 'https://go.dev/ref/spec#Statements', 'GO.ACTION'),
  ('Go', 'Go Spec §The zero value', 'https://go.dev/ref/spec#The_zero_value', 'GO.OBJECT'),
  ('Go', 'Go Spec §Types', 'https://go.dev/ref/spec#Types', 'GO.OBJECT'),
  ('Go', 'Go Spec §Variables', 'https://go.dev/ref/spec#Variables', 'GO.SUBJECT'),
  ('CommonLisp', 'CL New Reference §3.1.1 Introduction to Environments', 'https://lisp-docs.github.io/cl-language-reference/chap-3/d-b-evaluation', 'COMMONLISP.SUBJECT'),
  ('Perl', 'Perl 5.44 perldata §Context', 'https://perldoc.perl.org/perldata#Context', 'PERL.ACTION, PERL.OBJECT, PERL.SUBJECT'),
  ('Perl', 'Perl 5.44 perldata §List value constructors', 'https://perldoc.perl.org/perldata#List-value-constructors', 'PERL.OBJECT'),
  ('Perl', 'Perl 5.44 perldata §Scalar values', 'https://perldoc.perl.org/perldata#Scalar-values', 'PERL.OBJECT, PERL.SUBJECT'),
  ('Perl', 'Perl 5.44 perldata §Variable names', 'https://perldoc.perl.org/perldata#Variable-names', 'PERL.SUBJECT'),
  ('Perl', 'Perl 5.44 perlfunc', 'https://perldoc.perl.org/perlfunc', 'PERL.ACTION'),
  ('Perl', 'Perl 5.44 perlop §Operator Precedence', 'https://perldoc.perl.org/perlop#Operator-Precedence-and-Associativity', 'PERL.ACTION, PERL.OBJECT'),
  ('Perl', 'Perl 5.44 perlsub', 'https://perldoc.perl.org/perlsub', 'PERL.ACTION, PERL.SUBJECT'),
  ('Perl', 'Perl 5.44 perlsyn §Compound Statements', 'https://perldoc.perl.org/perlsyn#Compound-Statements', 'PERL.ACTION'),
  ('Perl', 'Perl 5.44 perlsyn §Foreach loop', 'https://perldoc.perl.org/perlsyn#Foreach-Loop', 'PERL.SUBJECT'),
  ('Perl', 'Perl 5.44 perlsyn §Loop Control', 'https://perldoc.perl.org/perlsyn#Loop-Control', 'PERL.ACTION'),
  ('Perl', 'Perl 5.44 perlvar §General variables', 'https://perldoc.perl.org/perlvar#General-variables', 'PERL.SUBJECT'),
  ('JavaScript', 'ECMAScript 2027 §9.1 Agent', 'https://tc39.es/ecma262/#sec-agent', 'JAVASCRIPT.SUBJECT'),
  ('JavaScript', 'ECMAScript 2027 §6.2.3 Completion Records', 'https://tc39.es/ecma262/#sec-completion-records', 'JAVASCRIPT.ACTION'),
  ('JavaScript', 'ECMAScript 2027 §6.1 ECMAScript Language Types', 'https://tc39.es/ecma262/#sec-ecmascript-language-types', 'JAVASCRIPT.OBJECT, TYPESCRIPT.OBJECT'),
  ('JavaScript', 'ECMAScript 2027 §6.2 ECMAScript Specification Types', 'https://tc39.es/ecma262/#sec-ecmascript-specification-types', 'JAVASCRIPT.OBJECT'),
  ('JavaScript', 'ECMAScript 2027 §9.4 Execution Contexts', 'https://tc39.es/ecma262/#sec-execution-contexts', 'JAVASCRIPT.ACTION, JAVASCRIPT.SUBJECT, TYPESCRIPT.SUBJECT'),
  ('JavaScript', 'ECMAScript 2027 §8 Syntax-Directed Operations', 'https://tc39.es/ecma262/#sec-syntax-directed-operations', 'JAVASCRIPT.ACTION, TYPESCRIPT.ACTION'),
  ('Haskell', 'Haskell 2010 §1 Introduction', 'https://www.haskell.org/onlinereport/haskell2010/haskellch1.html', 'HASKELL.ACTION, HASKELL.OBJECT, HASKELL.SUBJECT'),
  ('Haskell', 'Haskell 2010 §3 Expressions', 'https://www.haskell.org/onlinereport/haskell2010/haskellch3.html', 'HASKELL.ACTION, HASKELL.OBJECT, HASKELL.SUBJECT'),
  ('Haskell', 'Haskell 2010 §5 Modules', 'https://www.haskell.org/onlinereport/haskell2010/haskellch5.html', 'HASKELL.SUBJECT'),
  ('Haskell', 'Haskell 2010 §6 Predefined Types and Classes', 'https://www.haskell.org/onlinereport/haskell2010/haskellch6.html', 'HASKELL.ACTION, HASKELL.OBJECT, HASKELL.SUBJECT'),
  ('CommonLisp', 'CLHS §3.1 Evaluation', 'https://www.lispworks.com/documentation/HyperSpec/Body/03_a.htm', 'COMMONLISP.ACTION, COMMONLISP.SUBJECT'),
  ('CommonLisp', 'CLHS §3.1.2.1 Form Evaluation', 'https://www.lispworks.com/documentation/HyperSpec/Body/03_aba.htm', 'COMMONLISP.SUBJECT'),
  ('CommonLisp', 'CLHS §3.1.2.1.1 Symbols as Forms', 'https://www.lispworks.com/documentation/HyperSpec/Body/03_abaa.htm', 'COMMONLISP.ACTION'),
  ('CommonLisp', 'CLHS §3.1.2.1.2 Conses as Forms', 'https://www.lispworks.com/documentation/HyperSpec/Body/03_abab.htm', 'COMMONLISP.ACTION, COMMONLISP.SUBJECT'),
  ('CommonLisp', 'CLHS §3.1.2.1.3 Self-Evaluating Objects', 'https://www.lispworks.com/documentation/HyperSpec/Body/03_abac.htm', 'COMMONLISP.OBJECT'),
  ('CommonLisp', 'CLHS §3.1.2.1.2.3 Function Forms', 'https://www.lispworks.com/documentation/HyperSpec/Body/03_abad.htm', 'COMMONLISP.ACTION'),
  ('CommonLisp', 'CLHS §4 Types', 'https://www.lispworks.com/documentation/HyperSpec/Body/04_a.htm', 'COMMONLISP.OBJECT'),
  ('Scala', 'Scala 3.4 Spec Preface', 'https://www.scala-lang.org/files/archive/spec/3.4/', 'SCALA.SUBJECT'),
  ('Scala', 'Scala 3.4 Spec §3 Types', 'https://www.scala-lang.org/files/archive/spec/3.4/03-types.html', 'SCALA.OBJECT'),
  ('Scala', 'Scala 3.4 Spec §5 Classes & Objects', 'https://www.scala-lang.org/files/archive/spec/3.4/05-classes-and-objects.html', 'SCALA.SUBJECT'),
  ('Scala', 'Scala 3.4 Spec §6 Expressions', 'https://www.scala-lang.org/files/archive/spec/3.4/06-expressions.html', 'SCALA.ACTION, SCALA.OBJECT'),
  ('Scala', 'Scala 3.4 Spec §6.18 For Comprehensions', 'https://www.scala-lang.org/files/archive/spec/3.4/06-expressions.html#for-comprehensions-and-for-loops', 'SCALA.ACTION'),
  ('Scala', 'Scala 3.4 Spec §6.6 Method Applications', 'https://www.scala-lang.org/files/archive/spec/3.4/06-expressions.html#method-applications', 'SCALA.ACTION'),
  ('Scala', 'Scala 3.4 Spec §8 Pattern Matching', 'https://www.scala-lang.org/files/archive/spec/3.4/08-pattern-matching.html', 'SCALA.ACTION'),
  ('TypeScript', 'TypeScript Handbook Everyday Types', 'https://www.typescriptlang.org/docs/handbook/2/everyday-types.html', 'TYPESCRIPT.ACTION, TYPESCRIPT.OBJECT, TYPESCRIPT.SUBJECT'),
  ('TypeScript', 'TypeScript Handbook Narrowing', 'https://www.typescriptlang.org/docs/handbook/2/narrowing.html', 'TYPESCRIPT.ACTION'),
  ('TypeScript', 'TypeScript Handbook Type Inference', 'https://www.typescriptlang.org/docs/handbook/2/type-inference.html', 'TYPESCRIPT.SUBJECT'),
  ('TypeScript', 'TypeScript Handbook Creating Types from Types', 'https://www.typescriptlang.org/docs/handbook/2/types-from-types.html', 'TYPESCRIPT.OBJECT'),
  ('TypeScript', 'TypeScript Do''s and Don''ts §General Types', 'https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#general-types', 'TYPESCRIPT.OBJECT'),
  ('TypeScript', 'TypeScript Handbook Enums', 'https://www.typescriptlang.org/docs/handbook/enums.html', 'TYPESCRIPT.OBJECT'),
  ('TypeScript', 'TypeScript Handbook Iterators and Generators', 'https://www.typescriptlang.org/docs/handbook/iterators-and-generators.html', 'TYPESCRIPT.ACTION'),
  ('TypeScript', 'TypeScript Handbook Namespaces and Modules', 'https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html', 'TYPESCRIPT.SUBJECT'),
  ('TypeScript', 'TypeScript Handbook Symbols', 'https://www.typescriptlang.org/docs/handbook/symbols.html', 'TYPESCRIPT.OBJECT'),
  ('TypeScript', 'TypeScript Handbook Type Inference', 'https://www.typescriptlang.org/docs/handbook/type-inference.html', 'TYPESCRIPT.ACTION');
