-- Seed data: LLM Specification — Gotcha vs Contraction
-- Updated with 35+ regions from 115 search log entries

INSERT INTO investigations (id, title, summary, tags) VALUES
  ('INV.LLM.SPEC.CONTRACT', 'Gotcha vs Contraction — LLM Specification Pattern',
   'Cross-region investigation into two complementary strategies for constraining LLM output: contraction (positive constraints, schemas, scope narrowing) and gotcha (negative constraints, hard stops, antipattern enumeration). Mechanistic, empirical, and practice-based evidence from 35+ regions worldwide.',
   'llm,prompt-engineering,constraint,specification,reward-hacking,negation');

INSERT INTO fundamentals (id, investigation_id, title, principle, mechanism, example, evidence) VALUES
  ('FUND.CONTRACTION', 'INV.LLM.SPEC.CONTRACT', 'Contraction',
   'Narrow output space via positive instruction, schema, and example',
   'Aligned with autoregressive prediction — gives model a target to generate toward. Processed in early layers, robust and reliable (Rocchetti & Ferrara)',
   '"Respond in \u22643 sentences. Output JSON with keys X,Y."',
   'Anthropic (US), OpenAI (US), IAB Europe (EU), LangGPT (CN), CRGC (HK), CAPITU (LATAM)'),
  ('FUND.GOTCHA.HARD', 'INV.LLM.SPEC.CONTRACT', 'Gotcha — hard stop',
   'Binary verifiable prohibition for safety/security boundaries',
   'Defines walls — model can comply deterministically; best paired with out-of-prompt enforcement',
   '"Never share credentials. Do not execute destructive DB operations."',
   'Context Patterns (US), AgentPatterns (US), IAB Europe (EU), LangGPT Rules (CN), SheriaSenseEA (AFR), X-Road (EE)'),
  ('FUND.GOTCHA.BEHAV', 'INV.LLM.SPEC.CONTRACT', 'Gotcha — behavioral (avoid)',
   'Negative constraint for style/tone — primes the forbidden concept via late-layer FFN override',
   'Explicit mention of what to avoid activates the representation the model must suppress. Processed in late layers, fragile. Larger models perform worse (inverse scaling)',
   '"Don''t be verbose" \u2192 model fixates on verbosity',
   'Semantic Gravity Wells (87.5% priming), Negative Instruction Cascade, Tohoku negation mispriming (JP), SNU inverse scaling (KR), Rocchetti & Ferrara (mechanism)');

INSERT INTO regions (id, investigation_id, name, description) VALUES
  ('R.US', 'INV.LLM.SPEC.CONTRACT', 'US/English', 'Anthropic, OpenAI, independent researchers, industry practice guides'),
  ('R.EU', 'INV.LLM.SPEC.CONTRACT', 'EU/Europe', 'IAB Europe, Oxford, HTWK Leipzig, HICSS Kassel, Dagstuhl, CERN'),
  ('R.CN', 'INV.LLM.SPEC.CONTRACT', 'China/East Asia', 'CAS, PKU, THU, ZJU, Renmin University, IAAR Shanghai, LangGPT'),
  ('R.JP', 'INV.LLM.SPEC.CONTRACT', 'Japan', 'Tohoku University, RIKEN AIP, Nagoya University, Waseda'),
  ('R.KR', 'INV.LLM.SPEC.CONTRACT', 'Korea', 'Seoul National University, KAIST, Allganize'),
  ('R.LATAM', 'INV.LLM.SPEC.CONTRACT', 'Latin America', 'Brazilian consortium, Inria Chile, UNLP Argentina'),
  ('R.AFR', 'INV.LLM.SPEC.CONTRACT', 'Africa', 'GenAI-ERA, Masakhane, U. Toronto/MIT, East African developers'),
  ('R.ME', 'INV.LLM.SPEC.CONTRACT', 'Middle East / Arabic', 'MBZUAI, KFUPM, UAE/Saudi Arabia research institutions'),
  ('R.IN', 'INV.LLM.SPEC.CONTRACT', 'India / South Asia', 'IIT Madras, Sarvam AI, AI4Bharat'),
  ('R.SEA', 'INV.LLM.SPEC.CONTRACT', 'Southeast Asia', 'AI Singapore, NUS, Singapore NRF'),
  ('R.RU', 'INV.LLM.SPEC.CONTRACT', 'Russia / Eastern Europe', 'Russian research consortium, T-tech'),
  ('R.HK', 'INV.LLM.SPEC.CONTRACT', 'Hong Kong', 'CUHK, HKU, HKUST, Huawei HKRC'),
  ('R.CA', 'INV.LLM.SPEC.CONTRACT', 'Canada', 'Vector Institute, University of Toronto, University of Waterloo, Mila'),
  ('R.AU', 'INV.LLM.SPEC.CONTRACT', 'Australia / Oceania', 'Macquarie University, UTS Sydney'),
  ('R.NO', 'INV.LLM.SPEC.CONTRACT', 'Scandinavia / Nordic', 'University of Copenhagen, University of Oslo, AI Sweden, University of Turku'),
  ('R.CH', 'INV.LLM.SPEC.CONTRACT', 'Switzerland', 'EPFL, ETH Zurich, Idiap Research Institute'),
  ('R.IL', 'INV.LLM.SPEC.CONTRACT', 'Israel', 'Dicta, AI21 Labs, Technion, Weizmann'),
  ('R.DE', 'INV.LLM.SPEC.CONTRACT', 'Germany', 'LMU Munich, MCML, DKFZ Heidelberg, KIT Karlsruhe'),
  ('R.FR', 'INV.LLM.SPEC.CONTRACT', 'France', 'INRIA, CNRS, Grenoble, LINAGORA Toulouse, OpenLLM-France'),
  ('R.ES', 'INV.LLM.SPEC.CONTRACT', 'Spain', 'Barcelona Supercomputing Center, University of Madrid'),
  ('R.TR', 'INV.LLM.SPEC.CONTRACT', 'Turkey / Central Europe', 'Turkish research consortium, D\u00fczce University, Charles University'),
  ('R.PL', 'INV.LLM.SPEC.CONTRACT', 'Poland', 'Wroc\u0142aw Tech, Jagiellonian University'),
  ('R.EE', 'INV.LLM.SPEC.CONTRACT', 'Estonia / Baltics', 'Tallinn University of Technology, TwinLadder Research'),
  ('R.IE', 'INV.LLM.SPEC.CONTRACT', 'Ireland', 'Trinity College Dublin, ADAPT Centre / DCU'),
  ('R.BENELUX', 'INV.LLM.SPEC.CONTRACT', 'Benelux', 'KU Leuven, University of Amsterdam, University of Groningen'),
  ('R.IT', 'INV.LLM.SPEC.CONTRACT', 'Italy', 'FBK Trento, University of Bologna, CNR Pisa');

INSERT INTO sources (id, investigation_id, region_id, institution, title, key_content, methodology) VALUES
  ('US.ANTHROPIC', 'INV.LLM.SPEC.CONTRACT', 'R.US', 'Anthropic', 'Prompting best practices',
   '"Tell Claude what to do instead of what not to do" — official best practice across all model-specific guides', 'Industry guidelines'),
  ('US.OPENAI', 'INV.LLM.SPEC.CONTRACT', 'R.US', 'OpenAI', 'Prompt engineering guide',
   'Positive framing; schemas over prose; enums over free text; structured outputs', 'Industry guidelines'),
  ('US.SEMGRAV', 'INV.LLM.SPEC.CONTRACT', 'R.US', 'EmergentMind / arXiv', 'Semantic Gravity Wells (arXiv 2601.08070)',
   'Negative constraint failure: p = \u03c3(-2.40 + 2.27\u00b7P\u2080); 87.5% priming failure, 12.5% override failure', 'Mechanistic: logit lens, activation patching, attention analysis'),
  ('US.CTX.PATTERNS', 'INV.LLM.SPEC.CONTRACT', 'R.US', 'Context Patterns', 'Negative Constraints: Context Engineering Pattern',
   'Hard stops (keep negative) vs behavioral shaping (always reframe positive)', 'Engineering practice synthesis'),
  ('US.TIANPAN', 'INV.LLM.SPEC.CONTRACT', 'R.US', 'Tian Pan (independent)', 'When Your Forbidden List Becomes a Recipe',
   'Ablate your forbidden list; most "do not" lines don''t help or backfire; move enforcement out-of-prompt', 'Production audit methodology'),
  ('US.AGENT.PATTERNS', 'INV.LLM.SPEC.CONTRACT', 'R.US', 'AgentPatterns.ai', 'Negative Space Instructions',
   'Negatives are binary/verifiable/greppable; pair with positive guidance; use hooks not instructions for must-never-fail', 'Engineering practice'),
  ('US.THERMAL.BASE', 'INV.LLM.SPEC.CONTRACT', 'R.US', 'The Neural Base', 'Positive instructions beat negative',
   'Positive framing reduces hallucination 15-30%; positive alone 85%, positive+schema 99%', 'Production benchmarking'),
  ('EU.IAB', 'INV.LLM.SPEC.CONTRACT', 'R.EU', 'IAB Europe', 'AI Prompting Guide',
   '"Lead with positive instructions, add minimum negatives for known issues"', 'Industry guidance'),
  ('EU.OXFORD', 'INV.LLM.SPEC.CONTRACT', 'R.EU', 'University of Oxford', 'Defining and Characterizing Reward Hacking',
   'First formal proof: unhackability requires restricting the policy set', 'Formal proof, MDP framework'),
  ('EU.NEG.CASCADE', 'INV.LLM.SPEC.CONTRACT', 'R.EU', 'Zenodo (CERN)', 'Negative Instruction Cascade',
   '>40% negatives \u2192 catastrophic breakdown; 3:1 positive:negative ratio threshold', 'Empirical instruction refinement'),
  ('CN.CFBENCH', 'INV.LLM.SPEC.CONTRACT', 'R.CN', 'ACL 2025', 'CFBench: Comprehensive Constraint Following Benchmark',
   '10-category constraint taxonomy; 1000 samples across 200+ scenarios', 'Benchmark construction + evaluation'),
  ('CN.LANGPT', 'INV.LLM.SPEC.CONTRACT', 'R.CN', 'LangGPT (Chinese OSS)', 'Structured Prompt Methodology',
   'Role \u2192 Profile \u2192 Skills \u2192 Goals \u2192 Constraints \u2192 Rules \u2192 Workflow \u2192 Output', 'Engineering methodology'),
  ('JP.TOHOKU.NEG', 'INV.LLM.SPEC.CONTRACT', 'R.JP', 'Tohoku University / RIKEN AIP', 'Negation Understanding in CoT Prompting',
   'LLMs misled by "only"/"not" \u2192 bias toward "no" even in 175B models', 'Controlled negation experiments with GPT-3 175B, OPT-66B'),
  ('KR.THUNDER', 'INV.LLM.SPEC.CONTRACT', 'R.KR', 'Seoul National University (ACL 2026)', 'Thunder-KoNUBench',
   'First systematic Korean negation understanding benchmark; 47 LLMs; degrades under negation', '4,784 instances, corpus-aligned'),
  ('KR.NEG.INVSCALE', 'INV.LLM.SPEC.CONTRACT', 'R.KR', 'SNU / OpenReview', 'Negated Instructions Inverse Scaling Law',
   'Larger LLMs perform WORSE on negation; humans (13yo) have ~31% gap over best LLMs', '9 NLP benchmarks, OPT 125M-175B, GPT-3'),
  ('LATAM.CAPITU', 'INV.LLM.SPEC.CONTRACT', 'R.LATAM', 'Brazilian research consortium (arXiv 2026)', 'CAPITU: Portuguese IF Benchmark',
   '59 instruction types, 7 categories; frontier 98.5%; Portuguese-specialized cost-efficient', 'Benchmark + 18 model evaluation'),
  ('AFR.SHERIA', 'INV.LLM.SPEC.CONTRACT', 'R.AFR', 'East African developer', 'SheriaSenseEA: Legal AI',
   'Two-tier constraint system: frontend context injection + backend refusal protocol', 'Angular + Firebase + Gemini'),
  ('ME.AR.IFEVAL', 'INV.LLM.SPEC.CONTRACT', 'R.ME', 'MBZUAI / HuggingFace', 'Arabic IFEval',
   'First Arabic IFEval with Arabic-specific constraints; Claude 72.5% Arabic vs 84.7% English', 'IFEval adaptation + expert validation'),
  ('IN.INDICIFEVAL', 'INV.LLM.SPEC.CONTRACT', 'R.IN', 'IIT Madras / AI4Bharat (arXiv Feb 2026)', 'IndicIFEval',
   'Verifiable instruction-following for 14 Indic languages; Hindi near English parity; Gemma family most robust', 'Benchmark construction + evaluation'),
  ('IN.SARVAM', 'INV.LLM.SPEC.CONTRACT', 'R.IN', 'Sarvam AI (India)', 'Sarvam-M',
   'IFEval-based curriculum; multilingual prompt strategy (40% EN, 40% native, 20% romanized)', 'SFT + GRPO RLVR'),
  ('SEA.IFEVAL', 'INV.LLM.SPEC.CONTRACT', 'R.SEA', 'AI Singapore', 'SEA-IFEval',
   'Multilingual IFEval for Indonesian, Javanese, Sundanese, Thai, Tagalog, Vietnamese', 'IFEval adaptation + native translation'),
  ('HK.CRGC', 'INV.LLM.SPEC.CONTRACT', 'R.HK', 'Chinese University of Hong Kong (arXiv Jun 2026)', 'CRGC: Constraint Relationship Graph Completion',
   'Bridge constraints reconcile conflicting requirements; reduces violations by 39%', 'Graph construction + automated bridge discovery'),
  ('HK.CONINSTRUCT', 'INV.LLM.SPEC.CONTRACT', 'R.HK', 'University of Hong Kong (AAAI 2026)', 'ConInstruct',
   '6 constraint types, 9 conflict types; DeepSeek-R1 91.5% F1; models detect but rarely communicate conflicts', 'Benchmark construction + LLM evaluation'),
  ('CA.IFSCALE', 'INV.LLM.SPEC.CONTRACT', 'R.CA', 'Arize AI (May 2026)', 'IFScale Follow-up',
   'Models 10x better at instruction following in one year; GPT-5.5 99% through 5,000 constraints', 'Keyword inclusion proxy across models'),
  ('AU.CARE', 'INV.LLM.SPEC.CONTRACT', 'R.AU', 'Macquarie University (ECAI 2025)', 'CARE: Dual-Agent Prompt Refinement',
   'Prompt decomposition + rule-based transformations with explicit validation constraints', 'Staged transformation pipeline'),
  ('AU.CAP', 'INV.LLM.SPEC.CONTRACT', 'R.AU', 'University of Technology Sydney (Nature 2026)', 'Culturally-Aware Prompting',
   'Cultural context as explicit positive instructions improves appropriateness without accuracy loss', '72 outputs, blind human ratings'),
  ('NO.DAMETA', 'INV.LLM.SPEC.CONTRACT', 'R.NO', 'University of Copenhagen (LREC 2026)', 'DAMETA: Danish Metaphor Benchmark',
   'Prompt framing shifts error type: informed of metaphor\u2192figurative, uninformed\u2192literal distractor', '900 instances, 7 models'),
  ('CH.LAMER', 'INV.LLM.SPEC.CONTRACT', 'R.CH', 'EPFL / ETH Zurich / Idiap', 'LAMER: Meta-RL for LLM Agents',
   'Cross-episode training induces exploration; 11.8-19.3% absolute gains over standard RL', 'Meta-RL with self-reflection'),
  ('IL.DICTALM', 'INV.LLM.SPEC.CONTRACT', 'R.IL', 'Dicta (arXiv Feb 2026)', 'Dicta-LM 3.0: Hebrew LLM',
   '30 manually curated Hebrew-specific IFEval constraints; sets new standard for Hebrew IF', 'Continued pre-training + SFT + GRPO'),
  ('DE.CAUSAL', 'INV.LLM.SPEC.CONTRACT', 'R.DE', 'LMU Munich / MCML (arXiv May 2026)', 'Causal Methods for LLM Development',
   'Formal causal framing of constraint effects in alignment, routing, evaluation', 'Causal inference methodology'),
  ('FR.MOSAIC', 'INV.LLM.SPEC.CONTRACT', 'R.FR', 'French research collaboration (EACL 2026)', 'MOSAIC: Modular IF Benchmark',
   'Compliance varies with constraint type, quantity, position; up to 20 constraints per prompt', 'Dynamic dataset + 5 LLM evaluation'),
  ('ES.DIDACTEXT', 'INV.LLM.SPEC.CONTRACT', 'R.ES', 'University of Madrid / Barcelona (2025)', 'Guided Prompting Didactext',
   'Process-oriented decomposition into 4 phases beats holistic prompting', '750 essays, holistic vs guided'),
  ('TR.TUDUM', 'INV.LLM.SPEC.CONTRACT', 'R.TR', 'Turkish research consortium (arXiv Jul 2026)', 'T\u00dcD\u00dcM: Turkish-Thinking Pipeline',
   'SFT improves Turkish reasoning but reduces accuracy; RL recovers partially', 'SFT + GRPO with Turkish-language rewards'),
  ('TR.PROMPT.FMT', 'INV.LLM.SPEC.CONTRACT', 'R.TR', 'D\u00fczce University (Jan 2026)', 'Turkish Prompt Format Study',
   'Custom Turkish prompt tags outperform defaults for Llama2/Phi3 on Turkish instructions', '5 prompt formats, 2 models, 2 datasets'),
  ('PL.PLLUM', 'INV.LLM.SPEC.CONTRACT', 'R.PL', 'Wroc\u0142aw Tech consortium (2025)', 'PLLuM Family',
   'Polish LLM 8B-70B with 77k instruction dataset; organic > synthetic for linguistic adaptation', 'Continual pre-training + SFT + DPO + RL'),
  ('EE.XROAD', 'INV.LLM.SPEC.CONTRACT', 'R.EE', 'Tallinn University of Technology (2026)', 'Sovereign LLM for X-Road',
   'Structured prompt: context + key-value fields + flags + JSON schema; recall 1.000', 'Guided zero-shot classification'),
  ('IE.ARTISAN', 'INV.LLM.SPEC.CONTRACT', 'R.IE', 'Trinity College Dublin (Jan 2025)', 'ARTISAN Instruction Framework',
   'A-R-T-I-S-A-N: 7-stage systematic prompt methodology; Specific Constraints as own stage', 'Systematic framework design');

INSERT INTO researchers (id, investigation_id, region_id, name, institution, focus) VALUES
  ('R.US.ANTHROPIC', 'INV.LLM.SPEC.CONTRACT', 'R.US', 'Anthropic prompt engineering team', 'Anthropic', 'Positive framing, XML structure'),
  ('R.US.OPENAI', 'INV.LLM.SPEC.CONTRACT', 'R.US', 'OpenAI prompt engineering team', 'OpenAI', 'Structured outputs, schemas'),
  ('R.US.TIANPAN', 'INV.LLM.SPEC.CONTRACT', 'R.US', 'Tian Pan', 'Independent', 'Forbidden list ablation'),
  ('R.EU.SKALSE', 'INV.LLM.SPEC.CONTRACT', 'R.EU', 'Joar Skalse, Nikolaus Howe', 'Oxford, Mila', 'Reward hacking formal definition'),
  ('R.EU.HILLIARD', 'INV.LLM.SPEC.CONTRACT', 'R.EU', 'Matty Hilliard', 'Independent', 'Negative Instruction Cascade'),
  ('R.CN.LIU', 'INV.LLM.SPEC.CONTRACT', 'R.CN', 'Shenghua Liu, Lingrui Mei', 'CAS / UCAS', 'Context Engineering survey'),
  ('R.CN.LANGPT', 'INV.LLM.SPEC.CONTRACT', 'R.CN', 'LangGPT community', 'Chinese OSS', 'Structured prompt methodology'),
  ('R.JP.SUZUKI', 'INV.LLM.SPEC.CONTRACT', 'R.JP', 'Jun Suzuki, Mengyu Ye', 'Tohoku University / RIKEN', 'Negation in CoT, mispriming'),
  ('R.KR.JUNG', 'INV.LLM.SPEC.CONTRACT', 'R.KR', 'Sungmok Jung, Yeonkyoung So', 'Seoul National University', 'Korean negation, inverse scaling'),
  ('R.LATAM.BONAS', 'INV.LLM.SPEC.CONTRACT', 'R.LATAM', 'Giovana Bon\u00e1s', 'Brazilian consortium', 'Portuguese IF benchmarks (CAPITU)'),
  ('R.ME.MBZUAI', 'INV.LLM.SPEC.CONTRACT', 'R.ME', 'MBZUAI team', 'MBZUAI, UAE', 'Arabic IFEval'),
  ('R.HK.WONG', 'INV.LLM.SPEC.CONTRACT', 'R.HK', 'Kam-Fai Wong, Zhengyi Zhao', 'CUHK', 'CRGC constraint graphs'),
  ('R.HK.HE', 'INV.LLM.SPEC.CONTRACT', 'R.HK', 'Xingwei He, Siu-Ming Yiu', 'University of Hong Kong', 'ConInstruct conflict detection'),
  ('R.CA.MCILRAITH', 'INV.LLM.SPEC.CONTRACT', 'R.CA', 'Sheila McIlraith', 'Vector / U of T', 'Desired Behavior Specifications'),
  ('R.AU.BASTA', 'INV.LLM.SPEC.CONTRACT', 'R.AU', 'Nardine Basta', 'Macquarie University', 'CARE prompt refinement'),
  ('R.NO.SAMUEL', 'INV.LLM.SPEC.CONTRACT', 'R.NO', 'David Samuel', 'University of Oslo', 'On-policy RL for low-resource'),
  ('R.CH.BRBIC', 'INV.LLM.SPEC.CONTRACT', 'R.CH', 'Maria Brbi\u0107', 'EPFL', 'LAMER meta-RL agents'),
  ('R.IL.SHMIDMAN', 'INV.LLM.SPEC.CONTRACT', 'R.IL', 'Shaltiel Shmidman', 'Dicta', 'Hebrew instruction-following LLMs'),
  ('R.DE.FRAUEN', 'INV.LLM.SPEC.CONTRACT', 'R.DE', 'Dennis Frauen', 'LMU Munich', 'Causal methods for LLM evaluation'),
  ('R.FR.PURPURA', 'INV.LLM.SPEC.CONTRACT', 'R.FR', 'Alberto Purpura', 'French research collaboration', 'MOSAIC IF benchmark'),
  ('R.PL.KOCON', 'INV.LLM.SPEC.CONTRACT', 'R.PL', 'Jan Koco\u0144', 'Wroc\u0142aw Tech', 'PLLuM Polish LLM family'),
  ('R.EE.SALMANOV', 'INV.LLM.SPEC.CONTRACT', 'R.EE', 'Parviz Salmanov', 'Tallinn University of Technology', 'Sovereign LLM for X-Road'),
  ('R.IE.ORAGHALLAIGH', 'INV.LLM.SPEC.CONTRACT', 'R.IE', 'Eamonn O''Raghallaigh', 'Trinity College Dublin', 'ARTISAN prompt framework');

INSERT INTO meta_analyses (id, investigation_id, title, key_finding, methodology, sample_description) VALUES
  ('MA.SEMGRAV', 'INV.LLM.SPEC.CONTRACT', 'Semantic Gravity Wells (arXiv 2601.08070)',
   'Negative constraint failure follows logistic curve p = \u03c3(-2.40 + 2.27\u00b7P\u2080); 87.5% priming failure',
   'Mechanistic: logit lens, activation patching', 'n=40,000 samples'),
  ('MA.NEGINST', 'INV.LLM.SPEC.CONTRACT', 'Negative Instruction Cascade (Zenodo 2025)',
   'Threshold at ~40% negatives \u2192 breakdown; 3:1 positive:negative ratio required',
   'Empirical instruction refinement', '3 versions'),
  ('MA.SKILLFUL', 'INV.LLM.SPEC.CONTRACT', 'How LLMs Follow Instructions: Skillful Coordination (Rocchetti & Ferrara 2026)',
   'No universal constraint mechanism; structural constraints in early layers, semantic in late; dynamic monitoring during generation',
   'Diagnostic probing + causal ablation across 9 tasks', '3 models, 9 tasks'),
  ('MA.CRGC', 'INV.LLM.SPEC.CONTRACT', 'CRGC (CUHK 2026)',
   'Bridge constraints reconcile conflicting requirements; reduces violations by 39%',
   'Knowledge graph + automated bridge discovery', '3 IF datasets'),
  ('MA.CONINSTRUCT', 'INV.LLM.SPEC.CONTRACT', 'ConInstruct (HKU, AAAI 2026)',
   '6 constraint types, 9 conflict types; DeepSeek-R1 91.5% F1; models detect but rarely communicate',
   'Benchmark + LLM evaluation', 'Multiple LLMs'),
  ('MA.CSE', 'INV.LLM.SPEC.CONTRACT', 'CSE (Vasileva 2026)',
   'Two-regime decay: 58% at k=1 \u2192 ~16% floor; independent failures; 5-6 constraint ceiling',
   'Deterministic verification across text + vision', '14 text models, 10 VLMs'),
  ('MA.IFSCALE', 'INV.LLM.SPEC.CONTRACT', 'IFScale Follow-up (Arize AI 2026)',
   'Models 10x better at IF in one year; GPT-5.5 99% through 5,000 constraints',
   'Keyword inclusion proxy', 'GPT-4.1 through GPT-5.5, Claude, Gemini'),
  ('MA.SPECGAME.RL', 'INV.LLM.SPEC.CONTRACT', 'Specification Gaming in Reasoning Models (arXiv 2605.02269)',
   'RL reasoning training increases gaming 32-170%; mitigations reduce but don''t eliminate',
   'Multi-environment evaluation', '8 settings, Grok/Claude/GPT/DeepSeek');

INSERT INTO gaps (id, investigation_id, description, severity, status) VALUES
  ('GAP.CROSS.MODEL', 'INV.LLM.SPEC.CONTRACT', 'No study compares gotcha/contraction effectiveness systematically across model families (Claude vs GPT vs Gemini vs Qwen)', 'high', 'not surfaced'),
  ('GAP.CROSS.LANG', 'INV.LLM.SPEC.CONTRACT', 'Negation Sensitivity Index not measured across languages — how does constraint type effectiveness vary by language?', 'high', 'not surfaced'),
  ('GAP.JP', 'INV.LLM.SPEC.CONTRACT', 'Japan — negation understanding well-studied but no systematic gotcha/contraction design pattern', 'medium', 'not surfaced'),
  ('GAP.KR', 'INV.LLM.SPEC.CONTRACT', 'Korea — negation and IF benchmarks exist but no pattern-level analysis', 'medium', 'not surfaced'),
  ('GAP.LATAM', 'INV.LLM.SPEC.CONTRACT', 'Latin America — strong IF benchmarks but no mechanistic work on constraint types', 'medium', 'not surfaced'),
  ('GAP.AFRICA', 'INV.LLM.SPEC.CONTRACT', 'Africa — active in instruction tuning but no constraint effectiveness trade-off studies', 'medium', 'not surfaced'),
  ('GAP.ME', 'INV.LLM.SPEC.CONTRACT', 'Middle East — strong Arabic IFEval but no mechanistic gotcha/contraction work', 'medium', 'not surfaced'),
  ('GAP.IN', 'INV.LLM.SPEC.CONTRACT', 'India — sparse; IndicIFEval and Sarvam-M found but no systematic pattern research', 'medium', 'not surfaced'),
  ('GAP.SEA', 'INV.LLM.SPEC.CONTRACT', 'Southeast Asia — strong SEA-IFEval but no gotcha/contraction analysis', 'medium', 'not surfaced'),
  ('GAP.RU', 'INV.LLM.SPEC.CONTRACT', 'Russia/EE — sparse; ru-promptriever relevant but no systematic research', 'medium', 'not surfaced'),
  ('GAP.HK', 'INV.LLM.SPEC.CONTRACT', 'Hong Kong — strong constraint graph theory but no production pattern engineering', 'low', 'not surfaced'),
  ('GAP.CA', 'INV.LLM.SPEC.CONTRACT', 'Canada — strong formal specification but no LLM-specific mechanistic work', 'low', 'not surfaced'),
  ('GAP.AU', 'INV.LLM.SPEC.CONTRACT', 'Australia — strong on instruction hierarchy but no cross-model gotcha comparison', 'low', 'not surfaced'),
  ('GAP.NO', 'INV.LLM.SPEC.CONTRACT', 'Scandinavia — strong low-resource LLM adaptation but no constraint pattern research', 'low', 'not surfaced'),
  ('GAP.CH', 'INV.LLM.SPEC.CONTRACT', 'Switzerland — strong meta-RL for agents but no constraint taxonomy work', 'low', 'not surfaced'),
  ('GAP.IL', 'INV.LLM.SPEC.CONTRACT', 'Israel — strong Hebrew-specific IF but no cross-lingual gotcha comparison', 'low', 'not surfaced'),
  ('GAP.DE', 'INV.LLM.SPEC.CONTRACT', 'Germany — strong causal methods but no mechanistic interpretability of constraint types', 'low', 'not surfaced'),
  ('GAP.FR', 'INV.LLM.SPEC.CONTRACT', 'France — strong modular compliance evaluation but no gotcha-specific work', 'low', 'not surfaced'),
  ('GAP.ES', 'INV.LLM.SPEC.CONTRACT', 'Spain — strong Iberian evaluation but no constraint pattern research', 'low', 'not surfaced'),
  ('GAP.TR', 'INV.LLM.SPEC.CONTRACT', 'Turkey — strong Turkish-specific prompt formats but no systematic constraint analysis', 'low', 'not surfaced'),
  ('GAP.PL', 'INV.LLM.SPEC.CONTRACT', 'Poland — strong Polish LLM development but no constraint pattern research', 'low', 'not surfaced'),
  ('GAP.EE', 'INV.LLM.SPEC.CONTRACT', 'Estonia/Baltics — strong production sovereign LLM deployment but no systematic pattern research', 'low', 'not surfaced'),
  ('GAP.IE', 'INV.LLM.SPEC.CONTRACT', 'Ireland — ARTISAN framework provides methodology but no empirical constraint type validation', 'low', 'not surfaced');
